services:
  app:
    build: .
    container_name: eggbot
    environment:
      - TOKEN=${TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - USER_ID=${USER_ID}
      - CHANNEL_ID=${CHANNEL_ID}
    restart: always