services:
  app:
    build: .
    container_name: eggbot
    environment:
      - TOKEN=${TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - USER_ID=${USER_ID}
      - LEADER_ID=${CHANNEL_ID}
      - BOT_CHANNEL_ID=${BOT_CHANNEL_ID}
      - ANNOUNCEMENT_CHANNEL_ID=${ANNOUNCEMENT_CHANNEL_ID}
      - HEART_CHANNEL_ID=${HEART_CHANNEL_ID}
      - NO_EXP_CHANNEL_ID_LIST=${NO_EXP_CHANNEL_ID_LIST}
      - ROLE_LIST=${ROLE_LIST}
    restart: always