name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup podman
        uses: redhat-actions/podman-setup@v2
        with:
          version: 'latest'

      - name: login to ghcr
        run: echo "${{ secrets.GHCR_PAT }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build image
        run: |
          podman pull ghcr.io/${{ github.actor }}/eggbot:latest || true
          podman build \
            --layers \
            --cache-from ghcr.io/${{ github.actor }}/eggbot:latest \
            -t ghcr.io/${{ github.actor }}/eggbot:${{ github.sha }} .

      - name: tag image
        run: podman tag ghcr.io/${{ github.actor }}/eggbot:${{ github.sha }} ghcr.io/${{ github.actor }}/eggbot:latest

      - name: push image
        run: |
          podman push ghcr.io/${{ github.actor }}/eggbot:${{ github.sha }}
          podman push ghcr.io/${{ github.actor }}/eggbot:latest